[workspace]

members = [
    "tests",
    "types",
    "lib/eth-bridge-lockscript-lib",
    "lib/eth-bridge-typescript-lib",
]

exclude = [
    "contracts/eth-light-client-typescript",
    "contracts/eth-bridge-lockscript",
]
